/**
 * Spec 8.1: never alter caption CONTENT, always offset caption TIMING. These
 * tests exist mostly to prove the first half — the words a lecturer wrote must
 * come out byte for byte.
 */

import { describe, expect, it } from 'vitest'

import { InvalidVttError, countCues, offsetVtt } from './vtt'

const SAMPLE = `WEBVTT - Lecture captions

NOTE
Generated by a captioning tool. This comment must survive.

STYLE
::cue { color: papayawhip; }

intro
00:00:01.000 --> 00:00:04.500 align:start position:10%
Welcome to the module.
Second line of the same cue.

00:01:59.750 --> 00:02:03.000
Timestamps with an arrow --> inside the text should not confuse it.

02:00:00.000 --> 02:00:05.000
A cue two hours in.
`

describe('offsetVtt', () => {
  it('shifts every cue by the offset', () => {
    const { text, cueCount } = offsetVtt(SAMPLE, 5)
    expect(cueCount).toBe(3)
    expect(text).toContain('00:00:06.000 --> 00:00:09.500')
    expect(text).toContain('00:02:04.750 --> 00:02:08.000')
    expect(text).toContain('02:00:05.000 --> 02:00:10.000')
  })

  it('never alters a single character of cue text', () => {
    const { text } = offsetVtt(SAMPLE, 5)
    expect(text).toContain('Welcome to the module.')
    expect(text).toContain('Second line of the same cue.')
    expect(text).toContain('Timestamps with an arrow --> inside the text should not confuse it.')
    expect(text).toContain('A cue two hours in.')
  })

  it('preserves identifiers, settings, comments and styling', () => {
    const { text } = offsetVtt(SAMPLE, 5)
    expect(text).toContain('WEBVTT - Lecture captions')
    expect(text).toContain('NOTE')
    expect(text).toContain('Generated by a captioning tool. This comment must survive.')
    expect(text).toContain('::cue { color: papayawhip; }')
    expect(text).toContain('intro')
    expect(text).toContain('align:start position:10%')
  })

  it('changes nothing but the timestamps', () => {
    const { text } = offsetVtt(SAMPLE, 5)
    const withoutTiming = (value: string) =>
      value.split('\n').filter((line) => !line.includes('-->') || line.startsWith('Timestamps'))
    expect(withoutTiming(text)).toEqual(withoutTiming(SAMPLE))
  })

  it('accepts the MM:SS.mmm short form and normalises it', () => {
    const short = 'WEBVTT\n\n00:10.000 --> 00:14.000\nShort form.\n'
    const { text } = offsetVtt(short, 5)
    expect(text).toContain('00:00:15.000 --> 00:00:19.000')
    expect(text).toContain('Short form.')
  })

  it('preserves CRLF line endings', () => {
    const crlf = 'WEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nHello.\r\n'
    const { text } = offsetVtt(crlf, 5)
    expect(text).toContain('\r\n')
    expect(text).toContain('00:00:06.000 --> 00:00:07.000')
  })

  it('accepts a byte order mark', () => {
    expect(() => offsetVtt('\uFEFFWEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHi.\n', 5)).not.toThrow()
  })

  it('rejects something that is not WebVTT, in words a person can act on', () => {
    expect(() => offsetVtt('1\n00:00:01,000 --> 00:00:02,000\nAn SRT file.\n', 5)).toThrow(
      InvalidVttError,
    )
    try {
      offsetVtt('not subtitles at all', 5)
    } catch (error) {
      expect((error as Error).message).toContain('WEBVTT')
    }
  })

  it('does not shift a zero offset', () => {
    const { text } = offsetVtt(SAMPLE, 0)
    expect(text).toContain('00:00:01.000 --> 00:00:04.500')
  })

  it('counts cues without touching the file', () => {
    // The sample deliberately includes a cue whose TEXT contains `-->`. The
    // WebVTT grammar forbids that, but a file breaking the rule should be
    // miscounted rather than mangled — so both functions ignore lines with no
    // actual timestamp, and agree.
    expect(countCues(SAMPLE)).toBe(3)
    expect(offsetVtt(SAMPLE, 5).cueCount).toBe(countCues(SAMPLE))
  })
})
